title: Nora Need Sleep
description: 一个温柔的数字生活空间，收录像素中的光影、生活节奏与慢日常。
url: "https://NoraNeedSleep.github.io"
baseurl: "" # 留空代表根目录，不加斜杠

# 作者信息（你可以修改）
author:
  name: Nora
  avatar: /assets/images/avatar.png
  bio: 喜欢阳光洒进窗户的早晨，也喜欢泳池边写作业的傍晚。

# 导航菜单（后续我们一起建立页面）
nav:
  - title: "About"
    url: /about/
  - title: "Sims"
    url: /sims/
  - title: "Videos"
    url: /videos/
  - title: "Mods"
    url: /mods/
  - title: "Notes"
    url: /notes/

# 使用的主题（Minimal Mistakes）
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# 启用功能插件
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name/

# 语言环境
locale: zh-CN

# 不显示站点页脚中的“Powered by”
minimal_mistakes_skin: default
